### ISSUE TITLE
Good try! Looking forward for more

### ISSUE THREAD

**Issue by stanlylau** [abhishekjaiswal92/string_calculator#1]
I like how you use the parameter tests for different scenarios in this kata.

The implementation is doing a bit too much for the tests (i.e. supports more than 2 numbers) from the perspective of [Three Laws of Test-Driven Development](http://programmer.97things.oreilly.com/wiki/index.php/The_Three_Laws_of_Test-Driven_Development).

The

``` csharp
int sumOfNumbers = 0;
```

that is passed to 

``` csharp
private static int ReturnSumIfInputNotEmpty(string input, int sum)
```

and is unused puzzles me.

Would like to see you go further with other scenarios. :smile:

**Comment by abhishekjaiswal92** [comment]
Hi Stanly, 

Thanks for the encouragement. Yes, I realized I am doing more than I am supposed to do and will keep an eye for it in future.
Th issue you pointed out is correct and it remains unused, I overlooked it during the development.
I have already removed it from the code.
